### ISSUE TITLE
Picker contents on iOS not visible, nor is it clickable -not functioning properly

### ISSUE THREAD

**Issue by AliaMYH** [sleighdogs/react-native-android-native-picker#3]
The picker on Android works fine. However, I just started editing my app for iOS and testing it and the picker does not display the contents ( ie the options inside ). I think for that reason it is also not clickable. 

It's just an empty view with a colored background that's unresponsive. Any idea what the issue is? 

The following code is what I'm using: it works perfectly on Android. The if condition should immediately display 'Loading' until the options are loaded, and then it should display whatever options are available depending on the conditions i've put. 

```
renderPicker() {
    if( this.state.region_options.length < 1 )
      {
        console.log('render dummy');
        return <Picker
          prompt = 'Regions'
          selectedValue={this.state.region}
          onValueChange={(itemValue, itemIndex) => this.setState({region: Number(itemValue) })}
          items = {[{value: '0', label: 'Loading'}]}
          >
            <View style={styles.pickerContent}><Text style={styles.pickerText}>Loading</Text></View>
        </Picker>
      }
    else
      {
        console.log('render real');
        return <Picker
          prompt = 'Regions'
          selectedValue={this.state.region}
          onValueChange={(itemValue, itemIndex) => this.setState({region: Number(itemValue) })}
          items = {this.state.region_options}
          >
          {
            (this.state.region != null ) ?
            (<View style={styles.pickerContent}><Text style={styles.pickerText}>{this.state.region_map.get(this.state.region.toString())}</Text></View>) :
            (<View style={styles.pickerContent}><Text style={styles.pickerText}>Choose Region</Text></View>)
          }
        </Picker>
      }
  }
```

I also use it here, with status options with the same behavior exhibited. It works on android but does not display properly on iOS. 

```
<Picker
                        prompt = 'Gender'
                        selectedValue={this.state.gender}
                        onValueChange={(itemValue, itemIndex) => this.setState({gender: itemValue })}
                        items = {[{value: 'M', label: 'Male'}, {value: 'F', label: 'Female'}]}
                        >
                        {
                          (this.state.gender ==='M'||this.state.gender ==='F') ?
                          (<View style={styles.pickerContent}><Text style={styles.pickerText}>{gender_map.get(this.state.gender)}</Text></View>) :
                          (<View style={styles.pickerContent}><Text style={styles.pickerText}>Choose Gender</Text></View>)
                        }

</Picker>
```

**Comment by jtovarnak** [comment]
This component is aiming to fix some issues with Android native picker and provide a way to have stylable picker component. We strongly encourage to use different solution for iOS - in our projects we are combining this package with `react-native-picker` for iOS for example.

That being said I made some adjustments to how this component reverts to react native `Picker` - unfortunately I don't have any access to iOS device at this moment so cannot fully test it, but it should be somehow better than before (but far from ideal I suppose).

**Comment by AliaMYH** [comment]
Ok, thank you for the feedback and response. I'll try out react-native-picker
